

export default class CommonConstants {

  /**
   * Height and width is 100%.
   * */
  static readonly FULL_PARENT: string = '100%';

  /**
   * Font weight.
   * */
  static readonly FONT_WEIGHT: number = 500;

  /**
   * Max lines.
   */
  static readonly MAX_LINES: number = 1;

  /**
   * TextInput layout weight.
   */
  static readonly TEXTINPUT_LAYOUT_WEIGHT: number = 1;

  /**
   * Bigger than 999999999 using scientific notation.
   */
  static readonly MAX_RESULT: number = 999999999;

  /**
   * Exponential count.
   */
  static readonly EXPONENTIAL_COUNT = 9;

  /**
   * Fixed count.
   */
  static readonly FIXED_COUNT = 2;
}