/**
 * Represents a text object.
 * 
 * This class is primarily used for encapsulating text information, providing a standardized method for handling text data.
 * The constructor accepts a string parameter to initialize the text information.
 * 
 * @param text The text information, used to initialize the text object.
 */
class Text{
  constructor(text: string){
    // Outputs the initialized text information to the console
    console.info(`Text ${text}`);
  }
}
